[project]
name = "testing"
version = "0.0.17"
description = "API Testing Suite for Go DDD Template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.31.0",
    "pytest>=8.0.0",
    "pytest-html>=4.1.1",
    "python-dotenv>=1.0.0",
]
